name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry lock
          poetry install --no-root
      
      - name: Debug Python
        run: |
          python --version
          which python

      - name: Debug Poetry
        run: |
          poetry --version
          which poetry
          head -n 10 poetry.lock

      - name: Debug Environment
        run: |
          env | sort
          ls -la
          ls -la .github/envs

      - name: Debug Mongo container
        run: |
          docker ps -a
          docker logs $(docker ps -a -q --filter "ancestor=mongo:6.0")
          ss -lnt | grep 27017 || true

      - name: Debug Vars for Tests
        run: |
          set -a
          source .github/envs/.env.test
          set +a
          echo "DB_HOST=$DB_HOST"
          echo "DB_USER=$DB_USER"
          echo "DB_PASS=$DB_PASS"

      - name: Debug MongoDB container
        run: |
          docker ps -a
          docker logs $(docker ps -a -q --filter "ancestor=mongo:6.0")

      - name: Run tests
        run: |
          set -a
          source .github/envs/.env.test
          set +a
          MODE=TEST PYTHONPATH=. poetry run pytest -v --cov=app --cov-report=term-missing --disable-warnings --maxfail=1
